# Generated by Django 4.0.6 on 2023-08-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('item_description', models.TextField()),
                ('stock', models.IntegerField()),
                ('image_url', models.ImageField(upload_to='static/product-image')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('item_description', models.TextField()),
                ('category', models.CharField(choices=[('1', 'Laptop'), ('2', 'Desktop'), ('3', 'Printer'), ('4', 'Accessories')], max_length=10)),
                ('stock', models.IntegerField()),
                ('image_url', models.ImageField(upload_to='static/product-image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='products.product')),
            ],
        ),
    ]
