# Generated by Django 4.0.6 on 2023-08-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_trendingproduct_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.trendingproduct')),
            ],
        ),
    ]
