# Generated by Django 4.0.6 on 2023-08-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recommendproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendproduct',
            name='recommend_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
