# Generated by Django 4.0.6 on 2023-08-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_recommendproduct_recommend_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('accessories', 'Accessories')], max_length=15),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
